name: Rotate
version: 1.1b
description: A plugin to help player rotate blocks.
author: BongoMice
main: org.bongomice.rotate.RotatePlugin

commands:
    rotate:
        description: Rotate those pesky Minecraft blocks.
        usage: /rotate tool|reset