# Configuration for Rotate 1.3
# Check the BukkitDev Page for Help
# http://dev.bukkit.org/server-mods/rotate

use-permissions: false
default-tool: -1
# Valid Ids are: 290, 291, 292, 293, 294 (Hoes); 271, 275, 258, 286, 279 (Axes);
#                270, 274, 257, 278, 285 (Pickaxes); 269, 273, 256, 284, 277 (Shovels);
#                267, 268, 272, 276, 283 (Swords); 280, 262 (Sticks & Arrows);
#                -1; If you don't want any default tool.
          