# Configuration for Rotate 1.6
# Check the BukkitDev Page for Help
# http://dev.bukkit.org/server-mods/rotate
# Valid Ids are: 290, 291, 292, 293, 294 (Hoes);
#                271, 275, 258, 286, 279 (Axes);
#                270, 274, 257, 278, 285 (Pickaxes);
#                269, 273, 256, 284, 277 (Shovels);
#                267, 268, 272, 276, 283 (Swords);
#                280, 262 (Sticks & Arrows);
#                -1; If you don't want any default tool.

use-permissions: false
default-tool: -1
save-players-tools: true

# Rotatable Blocks: If you do not want your players to rotate a kind of block,
#                   write false in front of its name. Ex: chest: false

rotatable_blocks:
  slab: true
  rail: true
  piston: true
  stair: true
  wood: true
  sign: true
  dispenser: true
  dropper: true
  furnace: true
  enderchest: true
  chest: true
  trapped_chest: true
  pumpkin: true
  jack_o_lantern: true
  head: true
  painting: true
