name: Rotate
version: 1.3
description: A plugin to help player rotate blocks.
author: BongoMice
main: org.bongomice.rotate.RotatePlugin

commands:
  rotate:
    description: Rotate those pesky Minecraft blocks.
    usage: /rotate tool|reset|getDefaultTool

permissions:
  rotate.*:
    description: Gives access to the Rotate Tool & Command
    children:
      rotate.access: true
  rotate.access:
    description: Gives access to the Rotate Tool & Command
    default: true
