name: Rotate
version: 1.3
description: A plugin to help player rotate blocks.
author: BongoMice
main: org.bongomice.rotate.RotatePlugin

commands:
  rotate:
    description: Rotate those pesky Minecraft blocks.
    usage: /rotate tool|reset|getDefaultTool|setDefaultTool(op only)

permissions:
  rotate.*:
    description: Gives access to the Rotate Tool & Command
    children:
      rotate.access: true
      rotate.set-default-tool: true
  rotate.access:
    description: Gives access to the Rotate Tool & Command
    default: true
  rotate.set-default-tool:
    description: Let the player set the default Rotate tool in the config
    default: op
